---
abstract: 'Match a string against a blacklist and a whitelist'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-BlackWhiteList
provides:
  String::BlackWhiteList:
    file: lib/String/BlackWhiteList.pm
    version: 1.100860
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Scalar::Util: 0
  Test::More: 0.88
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=String-BlackWhiteList
  homepage: http://search.cpan.org/dist/String-BlackWhiteList/
  repository: http://github.com/hanekomu/String-BlackWhiteList
version: 1.100860
